Migration: GitHub Actions
vegastrike/Assets-Production pull request #44
Opened 2021-01-13 06:27 UTC by BenjamenMeyer

- Add GitHub Actions for CI and CD (based off the functionality
  from the Engine)
- Add Issue Templates for bugs and features
- Add links to the communities
- Add a pull request template

2021-01-13 06:28 UTC, BenjamenMeyer commented
This covers master after we've gotten this done then we can port to satisfy #43.

2021-01-13 10:01 UTC, stephengtuggy requested changes
Looks good overall; just a few things we might want to change

2021-01-13 10:01 UTC, stephengtuggy commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
Maybe add the `'bug'` label to bug reports by default?

2021-01-13 10:01 UTC, stephengtuggy commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Read up at the Vega Strike Wiki
Might want to add something about the Security mailing list as well

2021-01-13 10:01 UTC, stephengtuggy commented on .github/ISSUE_TEMPLATE/feature_request.md
> +labels: ''
Maybe add the `'enhancement'` label to feature requests by default?

2021-01-13 10:01 UTC, stephengtuggy commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
Debian buster isn't necessary because we have Debian stretch as well

2021-01-13 10:01 UTC, stephengtuggy commented on .github/workflows/gh-actions-pr.yml
> +          #  FLAGS:    '-DUSE_PYTHON_3=ON'
For Pull Request purposes, maybe we do want to build all of these, after all?

2021-01-13 10:01 UTC, stephengtuggy commented on .github/pull_request_template.md
> +Thank you for submitting a pull request and becoming a contributor to the Vega Strike: Upon the Coldest Sea.
Omit `the` before `Vega Strike`

2021-01-13 15:21 UTC, BenjamenMeyer commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Read up at the Vega Strike Wiki
yeah...not sure how to include mailing lists in there yet so I'm going to wait on those. Probably just use the `mailto://` URL format. I'm going to leave that to a follow-on PR.

2021-01-13 15:22 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-pr.yml
> +          #  FLAGS:    '-DUSE_PYTHON_3=ON'
I was matching the old Travis-CI config which only did one. It's not as big a deal on the Assets side as that's mostly Python. I'm game either way though.

2021-01-13 15:27 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
prefer Buster (Debian 10) over Stretch (Debian 9) (https://wiki.debian.org/DebianReleases)

2021-01-14 02:06 UTC, stephengtuggy commented on .github/workflows/gh-actions-pr.yml
> +          #  FLAGS:    '-DUSE_PYTHON_3=ON'
We can leave it as is for now.

2021-01-14 02:09 UTC, stephengtuggy commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
> 
> 
> prefer Buster (Debian 10) over Stretch (Debian 9) (https://wiki.debian.org/DebianReleases)

Understood. In general, yes, that is true: Debian Buster is preferred over Stretch. However, when it comes to building .debs, I think it's best to build on the oldest .deb-based platform we support. That way, we don't have to worry about backward compatibility of the .deb format, or any system dependencies, etc.

2021-01-14 02:10 UTC, stephengtuggy commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
So do we still support Debian stretch at this point?

2021-01-14 03:09 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
I'll have to double-check but iirc we do

2021-01-14 03:34 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
Okay checked (and updated) https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Platform-Support and we do still support Stretch for the time being as its the Debian LTS release. Buster is Debian Current. I think we have about 9 months left before LTS/Current change up based on https://wiki.debian.org/DebianReleases.

2021-01-14 03:44 UTC, stephengtuggy commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
OK

2021-01-14 03:44 UTC, BenjamenMeyer commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Read up at the Vega Strike Wiki
@stephengtuggy added something using https://mailtolinkgenerator.com/ to generate the full link.

2021-01-14 03:45 UTC, BenjamenMeyer commented on .github/workflows/gh-actions-release.yml
> +            FLAGS:    '-DUSE_PYTHON_3=ON'
Changed from Buster to Stretch; we'll probably update it to Buster in about 6-9 months

2021-01-14 03:47 UTC, stephengtuggy approved these changes
LGTM!

2021-01-14 03:49 UTC, merged