Add ships.json sample file
vegastrike/Assets-Production pull request #98
Opened 2022-10-20 19:30 UTC by royfalk

This file to eventually contain all ships from units.json
Related to [#739](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/739)

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- See other MR

2022-10-21 19:50 UTC, stephengtuggy requested changes
Need to add the new ships.json file to CMakeLists.txt. This will need to be done every time we add asset files.

2022-10-22 09:05 UTC, royfalk commented
> 



> 

We've not done so for units.json or units.csv and really all other assets.
We've only done so for unit.json for testing.

Did you mean 'every time we add asset files to testing'?

2022-10-27 14:46 UTC, BenjamenMeyer commented on units/ships.json
> +                "Prohibited_Upgrades": "upgrades/Overdrive:1;upgrades/Capacitors:1;upgrades/Reactors:1;upgrades/Armor:1;upgrades/Sensors:1;upgrades/Shield_Systems:1;upgrades/Passenger_Quarters:1;upgr
It would be good to break these down as well. guessing that needs another round of refactor so not blocking, just noting.

2022-10-27 14:47 UTC, BenjamenMeyer commented
@royfalk we need to add the JSON files - and presumably should have added the CSV files - into the CMake data so it gets installed properly; similar to how the documentation/manpages are added.

2022-10-29 20:12 UTC, stephengtuggy commented
@royfalk The last couple of files we added to the assets, I added to CMake for you, in followup PR's. :-) It definitely does need to be done.

2022-11-01 23:33 UTC, stephengtuggy approved these changes
Looks good to me

2022-11-01 23:33 UTC, merged